/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExpansionPanelBasic: typeof import('./components/expansions/ExpansionPanelBasic.vue')['default']
    ExpansionPanelDynamic: typeof import('./components/expansions/ExpansionPanelDynamic.vue')['default']
    ExpansionPanelFaq: typeof import('./components/expansions/ExpansionPanelFaq.vue')['default']
    ExpansionPanelForm: typeof import('./components/expansions/ExpansionPanelForm.vue')['default']
    FormEasy: typeof import('./components/forms/FormEasy.vue')['default']
    FormEasy01: typeof import('./components/forms/FormEasy01.vue')['default']
    FormEasy02: typeof import('./components/forms/FormEasy02.vue')['default']
    FormHard01: typeof import('./components/forms/FormHard01.vue')['default']
    FormHard02: typeof import('./components/forms/FormHard02.vue')['default']
    FormMedium: typeof import('./components/forms/FormMedium.vue')['default']
    FormMedium01: typeof import('./components/forms/FormMedium01.vue')['default']
    FormMedium02: typeof import('./components/forms/FormMedium02.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
