/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExpansionPanelBasic: typeof import('./components/expansions/ExpansionPanelBasic.vue')['default']
    ExpansionPanelFaq: typeof import('./components/expansions/ExpansionPanelFaq.vue')['default']
    ExpansionPanelForm: typeof import('./components/expansions/ExpansionPanelForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
