/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/expansions/expansion_panel_basic': RouteRecordInfo<'/expansions/expansion_panel_basic', '/expansions/expansion_panel_basic', Record<never, never>, Record<never, never>>,
    '/expansions/expansion_panel_dynamic': RouteRecordInfo<'/expansions/expansion_panel_dynamic', '/expansions/expansion_panel_dynamic', Record<never, never>, Record<never, never>>,
    '/expansions/expansion_panel_faq': RouteRecordInfo<'/expansions/expansion_panel_faq', '/expansions/expansion_panel_faq', Record<never, never>, Record<never, never>>,
    '/expansions/expansion_panel_form': RouteRecordInfo<'/expansions/expansion_panel_form', '/expansions/expansion_panel_form', Record<never, never>, Record<never, never>>,
    '/forms/form_easy_01': RouteRecordInfo<'/forms/form_easy_01', '/forms/form_easy_01', Record<never, never>, Record<never, never>>,
    '/forms/form_easy_02': RouteRecordInfo<'/forms/form_easy_02', '/forms/form_easy_02', Record<never, never>, Record<never, never>>,
    '/forms/form_hard_01': RouteRecordInfo<'/forms/form_hard_01', '/forms/form_hard_01', Record<never, never>, Record<never, never>>,
    '/forms/form_hard_02': RouteRecordInfo<'/forms/form_hard_02', '/forms/form_hard_02', Record<never, never>, Record<never, never>>,
    '/forms/form_medium_01': RouteRecordInfo<'/forms/form_medium_01', '/forms/form_medium_01', Record<never, never>, Record<never, never>>,
    '/forms/form_medium_02': RouteRecordInfo<'/forms/form_medium_02', '/forms/form_medium_02', Record<never, never>, Record<never, never>>,
  }
}
